{
 "title": "OPEN5GS & UERANSIM",
 "time": { "from": "now-117m", "to": "now-97m" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "AMF Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amf_session{job=\"open5gs-amf-metrics\"}",
     "legendFormat": "AMF Sessions"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "# Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Uso de recursos de memoria por cada pod",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "memory_usage{pod_name!~\".*prometheus.*|.*mongodb.*|.*webui.*|.*populate.*|.*pod-metrics.*|.*grafana.*\"}/1024",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Uso de recursos de cpu por cada pod",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cpu_usage{pod_name!~\".*prometheus.*|.*mongodb.*|.*webui.*|.*populate.*|.*pod-metrics.*|.*grafana.*\"} / 1000000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Iperf3 Setup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Latency Ping3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "ping3_latency{job=\"ue-metrics\"}",
     "legendFormat": "UE-Iperf3"
    }
   ]
  },
  {
   "title": "Throughput mean (last 1m)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg_over_time(iperf3_throughput{job=\"ue-metrics\"}[1m])/1000000",
     "legendFormat": "UE-Iperf3"
    }
   ]
  },
  {
   "title": "Ping3 mean (last 1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(ping3_latency{job=\"ue-metrics\"}[1m])",
     "legendFormat": "Latency"
    },
    {
     "expr": "avg_over_time(ping3_jitter{job=\"ue-metrics\"}[1m])",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "MOS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "(\n  (0.6 * (1 - (avg_over_time(ping3_jitter{job=\"ue-metrics\"}[1m]) / max_over_time(ping3_jitter{job=\"ue-metrics\"}[24h])))) +\n  (0.5 * (1 - (avg_over_time(ping3_latency{job=\"ue-metrics\"}[1m]) / max_over_time(ping3_latency{job=\"ue-metrics\"}[24h])))) +\n  (0.1 * (avg_over_time(iperf3_throughput{job=\"ue-metrics\"}[1m]) / max_over_time(iperf3_throughput{job=\"ue-metrics\"}[24h])))\n)\n*\n(4.23 - 1) + 1",
     "legendFormat": "Iperf3"
    }
   ]
  },
  {
   "title": "Throughput Iperf3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "iperf3_throughput{job=\"ue-metrics\"}/1000000",
     "legendFormat": "UE-Iperf3"
    },
    { "legendFormat": "UE Lost" }
   ]
  },
  {
   "title": "Jitter Ping3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "ping3_jitter{job=\"ue-metrics\"}",
     "legendFormat": "UE Throughput"
    },
    { "legendFormat": "UE Lost" }
   ]
  },
  {
   "title": "Youtube Setup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Youtube VS iperf3",
     "type": "timeseries",
     "description": "Uso de recursos de cpu por cada pod",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "cpu_usage{pod_name=\"ues2-ueransim-ues-6c64d849fd-vj4rs\"} / 1000000",
       "legendFormat": "UE-iperf3"
      },
      {
       "expr": "cpu_usage{pod_name=\"ueransim-ueransim-gnb-ues-fb94cfd4c-7884l\"} / 1000000",
       "legendFormat": "UE-youtube"
      }
     ]
    },
    {
     "title": "youtube Resolution displayed (%)",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 8, "x": 12, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Resolution_displayed_percentage_144p{job=\"ue-metrics\"}",
       "legendFormat": "144p"
      },
      {
       "expr": "Resolution_displayed_percentage_240p{job=\"ue-metrics\"}",
       "legendFormat": "240p"
      },
      {
       "expr": "Resolution_displayed_percentage_360p{job=\"ue-metrics\"}",
       "legendFormat": "360p"
      },
      {
       "expr": "Resolution_displayed_percentage_480p{job=\"ue-metrics\"}",
       "legendFormat": "480p"
      },
      {
       "expr": "Resolution_displayed_percentage_720p{job=\"ue-metrics\"}",
       "legendFormat": "720p"
      },
      {
       "expr": "Resolution_displayed_percentage_1080p{job=\"ue-metrics\"}",
       "legendFormat": "1080p"
      },
      {
       "expr": "Resolution_displayed_percentage_2K{job=\"ue-metrics\"}",
       "legendFormat": "2K"
      },
      {
       "expr": "Resolution_displayed_percentage_4K{job=\"ue-metrics\"}",
       "legendFormat": "4K"
      }
     ]
    },
    {
     "title": "youtube MOS",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 3, "x": 20, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mos{job=\"ue-metrics\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Network Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "# Connections attempted AMF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_attempted_total{dialer_name=\"open5gs-amf-metrics\"}",
     "legendFormat": "AMF Sessions"
    }
   ]
  },
  {
   "title": "# Connections closed AMF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_closed_total{dialer_name=\"open5gs-amf-metrics\"}",
     "legendFormat": "AMF Sessions"
    }
   ]
  },
  {
   "title": "# Connections established AMF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_established_total{dialer_name=\"open5gs-amf-metrics\"}",
     "legendFormat": "AMF Sessions"
    }
   ]
  },
  {
   "title": "# Connections attempted SMF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_attempted_total{dialer_name=\"open5gs-smf-metrics\"}",
     "legendFormat": "AMF Sessions"
    }
   ]
  },
  {
   "title": "# Connection failed AMF",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_failed_total{dialer_name=\"open5gs-amf-metrics\", reason=\"refused\"}",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "net_conntrack_dialer_conn_failed_total{dialer_name=\"open5gs-amf-metrics\", reason=\"resolution\"}",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "net_conntrack_dialer_conn_failed_total{dialer_name=\"open5gs-amf-metrics\", reason=\"timeout\"}",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "net_conntrack_dialer_conn_failed_total{dialer_name=\"open5gs-amf-metrics\", reason=\"unknown\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}