apiVersion: v1
kind: Service
metadata: 
  name: ue-metrics-service
spec: 
  selector: 
    "app.kubernetes.io/component": "ues"
  ports:
    - name: service-port
      protocol: TCP
      port: 8000
      targetPort: 8000



